### ISSUE TITLE
Please check METAR Error

### ISSUE THREAD

**Issue by HSPHU** [jbud/Flex-Calculator-TS#10]
"root":{4 items
"message":string"Network Error"
"name":string"Error"
"stack":string"Error: Network Error at e.exports (https://jbud.github.io/Flex-Calculator-TS/static/js/main.08d7db70.js:2:71618) at h.onerror (https://jbud.github.io/Flex-Calculator-TS/static/js/main.08d7db70.js:2:67271)"
"config":{11 items
"url":string"https://api.flybywiresim.com/metar/ZSPD?source=vatsim"
"method":string"get"
"headers":{...}1 item
"transformRequest":[...]1 item
"transformResponse":[...]1 item
"timeout":int0
"xsrfCookieName":string"XSRF-TOKEN"
"xsrfHeaderName":string"X-XSRF-TOKEN"
"maxContentLength":int-1
"maxBodyLength":int-1
"transitional":{...}3 items
}
}

**Comment by jbud** [comment]
Metar currently uses flybywire api. I'm currently investigating a backup api as fbw is having some issues

**Comment by HSPHU** [comment]
Please check the API database. I attempted to use A339 to calculate all airports but received an error below.
"INVALID TAKEOFF CAUSED BY CALCULATED DISTANCE REQUIRED LONGER THAN TORA EVEN WITH TOGA THRUST TRY A HIGHER FLAPS SETTING OR A LONGER RUNWAY"

**Comment by jbud** [comment]
fixed in a90f3a4
